[package]
name = "research_rust"
version = "0.1.0"
authors = ["Jonathan Rotter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99.0"